export { BRAND_NAMES, FAMILY, type Brand } from './brands.js'
export { consentSentences, type ConsentSentences } from './sentences.js'
export { CONSENT_TEMPLATE_VERSION, consentVersion } from './version.js'
export { INITIAL_CONSENT, consentFlags, type ConsentScope, type ConsentState } from './state.js'
export { CONSENT_EVENTS } from './events.js'
